name: api_ml_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - numpy
  - pandas
  - pandas-profiling=2.11.0
  - scikit-learn
  - pip=20.3.3
  - pytest
  - requests
  - fastapi==0.65.2
  - uvicorn
  - gunicorn
  - flake8  